name: Expected filenames

on:
  pull_request:
    paths:
      - '*[gG][oO][lL][dD][eE][nN]*'
      - '**/*[gG][oO][lL][dD][eE][nN]*'
      - '!vendor/**'

permissions:
  contents: read

jobs:
  expected-filenames:
    name: no golden filenames
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      - name: Check tracked filenames
        run: scripts/check-expected-filenames.sh
